import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 'section-1',
    label: 'Seção 1 · Unidade 1',
    title: 'Fundamentos de IA',
    unlocked: true,
    lessons: [
      {
        icon: '⭐',
        title: 'O que é Inteligência Artificial?',
        description: 'Explore a história e os fundamentos da IA moderna.',
        topics: [
          'História da IA desde 1950',
          'Diferença entre IA, ML e DL',
          'Tipos de aprendizado',
          'Aplicações reais no dia a dia',
        ],
        questions: [
          {
            icon: '🤖', category: 'Conceitos', difficulty: 'Fácil',
            text: 'Qual é a definição mais precisa de Inteligência Artificial?',
            options: ['Robôs físicos que pensam', 'Sistemas que simulam capacidades cognitivas humanas', 'Qualquer software computacional', 'Programas de videogame'],
            correctIndex: 1,
            explanation: 'IA é o campo da ciência da computação que busca criar sistemas capazes de simular capacidades intelectuais humanas como aprender, raciocinar e resolver problemas.',
          },
          {
            icon: '📅', category: 'Conceitos', difficulty: 'Fácil',
            text: 'Quem é considerado o "pai" da Inteligência Artificial?',
            options: ['Alan Turing', 'John McCarthy', 'Elon Musk', 'Marvin Minsky'],
            correctIndex: 1,
            explanation: 'John McCarthy cunhou o termo "Inteligência Artificial" em 1956, durante a famosa Conferência de Dartmouth.',
          },
          {
            icon: '🧠', category: 'Conceitos', difficulty: 'Médio',
            text: 'O que diferencia Machine Learning de IA clássica (regras)?',
            options: ['ML é mais rápido', 'ML aprende padrões com dados sem regras explícitas', 'ML só funciona com imagens', 'ML precisa de mais código'],
            correctIndex: 1,
            explanation: 'IA clássica usa regras criadas manualmente por humanos. Machine Learning permite que o sistema aprenda os próprios padrões a partir de dados.',
          },
          {
            icon: '🔢', category: 'Conceitos', difficulty: 'Médio',
            text: 'O que são "dados de treinamento" em Machine Learning?',
            options: ['Documentação do sistema', 'Exemplos históricos usados para o modelo aprender', 'Logs de erro do servidor', 'Hiperparâmetros do modelo'],
            correctIndex: 1,
            explanation: 'Dados de treinamento são os exemplos que o modelo usa para aprender padrões. Quanto mais dados de qualidade, melhor o aprendizado.',
          },
          {
            icon: '🔍', category: 'Conceitos', difficulty: 'Fácil',
            text: 'O que é "Deep Learning"?',
            options: ['Aprendizado muito lento', 'Subárea de ML com redes neurais de múltiplas camadas', 'Treinamento feito por humanos', 'Uma linguagem de programação'],
            correctIndex: 1,
            explanation: 'Deep Learning usa redes neurais artificiais com muitas camadas. É a tecnologia por trás de reconhecimento de voz, imagens e LLMs como o ChatGPT.',
          },
          {
            icon: '🎯', category: 'Conceitos', difficulty: 'Médio',
            text: 'O que é aprendizado supervisionado?',
            options: ['IA que aprende sem professor', 'IA treinada com pares de entrada e saída rotulados', 'IA que aprende por tentativa e erro', 'IA que usa apenas texto'],
            correctIndex: 1,
            explanation: 'No aprendizado supervisionado, o modelo recebe exemplos rotulados. Ele aprende a mapear entradas em saídas corretas.',
          },
          {
            icon: '💡', category: 'Conceitos', difficulty: 'Difícil',
            text: 'O que é "Transfer Learning"?',
            options: ['Transferir dados entre servidores', 'Usar conhecimento de um modelo pré-treinado em nova tarefa', 'Copiar pesos entre projetos', 'Migrar entre cloud providers'],
            correctIndex: 1,
            explanation: 'Transfer Learning reutiliza um modelo treinado em uma tarefa e o adapta para outra. Economiza tempo e dados enormemente.',
          },
          {
            icon: '⚖️', category: 'Ética', difficulty: 'Médio',
            text: 'O que é "viés algorítmico" em IA?',
            options: ['IA que prefere Python a JavaScript', 'Discriminação sistemática resultante de dados tendenciosos', 'Bug de cálculo matemático', 'Alta taxa de erro aleatório'],
            correctIndex: 1,
            explanation: 'Viés algorítmico ocorre quando o modelo replica preconceitos presentes nos dados de treinamento.',
          },
        ],
      },
      {
        icon: '🧠',
        title: 'Machine Learning na Prática',
        description: 'Entenda como algoritmos aprendem com dados.',
        topics: ['Tipos de ML', 'Dados de treino e teste', 'Métricas de avaliação', 'Casos de uso reais'],
        questions: [
          {
            icon: '📊', category: 'ML', difficulty: 'Fácil' as const,
            text: 'Qual é o objetivo principal do Machine Learning?',
            options: ['Substituir programadores', 'Aprender padrões a partir de dados automaticamente', 'Criar interfaces bonitas', 'Acelerar a internet'],
            correctIndex: 1,
            explanation: 'ML permite que sistemas aprendam e melhorem automaticamente com experiência, sem serem explicitamente programados.',
          },
          {
            icon: '🔢', category: 'ML', difficulty: 'Médio' as const,
            text: 'O que é um dataset de teste?',
            options: ['Dados usados para treinar', 'Dados reservados para avaliar o modelo', 'Dados descartados', 'Dados duplicados'],
            correctIndex: 1,
            explanation: 'O dataset de teste é separado do treino para avaliar quão bem o modelo generaliza para dados novos.',
          },
          {
            icon: '📈', category: 'ML', difficulty: 'Médio' as const,
            text: 'O que é acurácia em ML?',
            options: ['Velocidade do modelo', 'Porcentagem de previsões corretas', 'Tamanho do dataset', 'Número de parâmetros'],
            correctIndex: 1,
            explanation: 'Acurácia mede a proporção de previsões corretas sobre o total de previsões feitas pelo modelo.',
          },
        ],
      },
      {
        icon: '💬',
        title: 'Processamento de Linguagem Natural',
        description: 'Como a IA entende e gera texto humano.',
        topics: ['Tokenização', 'Embeddings', 'Modelos de linguagem', 'Chatbots e assistentes'],
        questions: [
          {
            icon: '💬', category: 'NLP', difficulty: 'Fácil' as const,
            text: 'O que é NLP (Processamento de Linguagem Natural)?',
            options: ['Linguagem de programação', 'Campo da IA que trabalha com linguagem humana', 'Protocolo de rede', 'Tipo de banco de dados'],
            correctIndex: 1,
            explanation: 'NLP é a área da IA que permite máquinas entenderem, interpretarem e gerarem linguagem humana.',
          },
          {
            icon: '🔤', category: 'NLP', difficulty: 'Médio' as const,
            text: 'O que são "embeddings" em NLP?',
            options: ['Imagens embutidas em texto', 'Representações numéricas de palavras em vetores', 'Links dentro do texto', 'Comentários no código'],
            correctIndex: 1,
            explanation: 'Embeddings convertem palavras em vetores numéricos que capturam significado semântico.',
          },
          {
            icon: '🤖', category: 'NLP', difficulty: 'Médio' as const,
            text: 'O que é um LLM (Large Language Model)?',
            options: ['Um banco de dados grande', 'Modelo treinado em bilhões de textos para gerar linguagem', 'Uma rede social', 'Um sistema operacional'],
            correctIndex: 1,
            explanation: 'LLMs como GPT são modelos massivos treinados em enormes quantidades de texto para entender e gerar linguagem.',
          },
        ],
      },
      {
        icon: '⚙️',
        title: 'Prompt Engineering',
        description: 'Aprenda a se comunicar melhor com a IA.',
        topics: ['Estrutura de prompts', 'Few-shot learning', 'Chain-of-Thought', 'Técnicas avançadas'],
        questions: [
          {
            icon: '✍️', category: 'Prompts', difficulty: 'Fácil' as const,
            text: 'O que é um "prompt" em IA generativa?',
            options: ['Código-fonte do modelo', 'Instrução ou texto de entrada dado ao modelo', 'Uma API REST', 'O resultado gerado'],
            correctIndex: 1,
            explanation: 'O prompt é o texto que você envia ao modelo de IA para obter uma resposta.',
          },
          {
            icon: '🎯', category: 'Prompts', difficulty: 'Médio' as const,
            text: 'O que é "few-shot prompting"?',
            options: ['Dar poucos comandos', 'Incluir exemplos no prompt para guiar a resposta', 'Usar modelos pequenos', 'Treinar com poucos dados'],
            correctIndex: 1,
            explanation: 'Few-shot prompting inclui alguns exemplos no prompt para o modelo entender o padrão esperado.',
          },
          {
            icon: '🧠', category: 'Prompts', difficulty: 'Difícil' as const,
            text: 'O que é "Chain-of-Thought" prompting?',
            options: ['Encadear vários modelos', 'Pedir ao modelo que mostre o raciocínio passo a passo', 'Usar blockchain com IA', 'Repetir o mesmo prompt'],
            correctIndex: 1,
            explanation: 'Chain-of-Thought pede ao modelo que raciocine passo a passo, melhorando respostas em problemas complexos.',
          },
        ],
      },
      {
        icon: '🎯',
        title: 'IA no Mundo Real',
        description: 'Aplicações práticas e ética da Inteligência Artificial.',
        topics: ['IA em empresas', 'Ética e viés', 'Regulamentação', 'Futuro da IA'],
        questions: [
          {
            icon: '🏢', category: 'Aplicações', difficulty: 'Fácil' as const,
            text: 'Qual área NÃO usa IA comumente hoje?',
            options: ['Diagnóstico médico', 'Recomendação de conteúdo', 'Fabricação de tijolos artesanais', 'Detecção de fraudes'],
            correctIndex: 2,
            explanation: 'IA é amplamente usada em saúde, entretenimento e finanças, mas processos puramente artesanais não dependem dela.',
          },
          {
            icon: '⚖️', category: 'Ética', difficulty: 'Médio' as const,
            text: 'Por que a regulamentação de IA é importante?',
            options: ['Para tornar a IA mais lenta', 'Para garantir uso responsável e proteger direitos', 'Para proibir toda automação', 'Para aumentar custos'],
            correctIndex: 1,
            explanation: 'Regulamentação visa garantir que IA seja usada de forma ética, transparente e sem prejudicar pessoas.',
          },
          {
            icon: '🚀', category: 'Futuro', difficulty: 'Médio' as const,
            text: 'O que é "IA responsável"?',
            options: ['IA que funciona sem bugs', 'Desenvolvimento de IA com foco em ética, transparência e inclusão', 'IA que responde rápido', 'IA open source'],
            correctIndex: 1,
            explanation: 'IA responsável considera impactos sociais, viés, privacidade e transparência no desenvolvimento de sistemas de IA.',
          },
        ],
      },
    ],
  },
  {
    id: 'section-2',
    label: 'Seção 2 · Unidade 2',
    title: 'Prompting Avançado',
    unlocked: false,
    lessons: [],
  },
];

export const FINAL_TEST_QUESTIONS = [
  {
    icon: '🤖', category: 'Fundamentos', difficulty: 'Médio' as const,
    text: 'Qual a principal diferença entre IA simbólica e IA conexionista?',
    options: ['Velocidade de processamento', 'Regras explícitas vs. aprendizado por padrões', 'Linguagem de programação usada', 'Custo de hardware'],
    correctIndex: 1,
    explanation: 'IA simbólica usa regras lógicas explícitas, enquanto IA conexionista (redes neurais) aprende padrões a partir de dados.',
  },
  {
    icon: '🧠', category: 'Machine Learning', difficulty: 'Médio' as const,
    text: 'Qual tipo de aprendizado é usado quando não temos dados rotulados?',
    options: ['Supervisionado', 'Não supervisionado', 'Por reforço', 'Transfer Learning'],
    correctIndex: 1,
    explanation: 'O aprendizado não supervisionado encontra padrões em dados sem rótulos, como agrupamentos e associações.',
  },
  {
    icon: '📊', category: 'Dados', difficulty: 'Fácil' as const,
    text: 'O que é "overfitting" em Machine Learning?',
    options: ['Modelo muito simples', 'Modelo que memoriza os dados de treino sem generalizar', 'Excesso de dados de treino', 'Modelo com poucos parâmetros'],
    correctIndex: 1,
    explanation: 'Overfitting ocorre quando o modelo aprende demais os detalhes dos dados de treino e falha em dados novos.',
  },
  {
    icon: '🔗', category: 'Deep Learning', difficulty: 'Difícil' as const,
    text: 'O que é uma função de ativação em redes neurais?',
    options: ['Função que liga o computador', 'Função que introduz não-linearidade nas camadas', 'Algoritmo de otimização', 'Método de coleta de dados'],
    correctIndex: 1,
    explanation: 'Funções de ativação como ReLU e Sigmoid permitem que redes neurais aprendam relações complexas e não-lineares.',
  },
  {
    icon: '💬', category: 'NLP', difficulty: 'Médio' as const,
    text: 'O que significa "tokenização" em Processamento de Linguagem Natural?',
    options: ['Criptografar texto', 'Dividir texto em unidades menores (tokens)', 'Traduzir entre idiomas', 'Comprimir arquivos de texto'],
    correctIndex: 1,
    explanation: 'Tokenização divide texto em pedaços (palavras, subpalavras ou caracteres) para que modelos de IA possam processá-los.',
  },
  {
    icon: '🎯', category: 'Modelos', difficulty: 'Difícil' as const,
    text: 'O que é o mecanismo de "Attention" em Transformers?',
    options: ['Filtro de spam', 'Mecanismo que permite o modelo focar em partes relevantes da entrada', 'Sistema de cache de memória', 'Técnica de compressão'],
    correctIndex: 1,
    explanation: 'O mecanismo de Attention permite que o modelo pondere a importância de cada parte da entrada, revolucionando o NLP.',
  },
  {
    icon: '⚡', category: 'Prática', difficulty: 'Fácil' as const,
    text: 'Qual dessas é uma aplicação real de IA generativa?',
    options: ['Calculadora simples', 'Geração de imagens a partir de texto', 'Planilha de Excel', 'Envio de e-mails automáticos'],
    correctIndex: 1,
    explanation: 'IA generativa como DALL-E e Midjourney criam imagens originais a partir de descrições em texto.',
  },
  {
    icon: '⚖️', category: 'Ética', difficulty: 'Médio' as const,
    text: 'O que é "explicabilidade" (XAI) em IA?',
    options: ['Manual de instrução do software', 'Capacidade de entender e justificar decisões do modelo', 'Velocidade de resposta', 'Interface do usuário'],
    correctIndex: 1,
    explanation: 'XAI busca tornar as decisões de modelos de IA transparentes e compreensíveis para humanos.',
  },
  {
    icon: '🔄', category: 'MLOps', difficulty: 'Difícil' as const,
    text: 'O que é "model drift" em produção?',
    options: ['Bug no código', 'Degradação do modelo quando dados reais mudam ao longo do tempo', 'Modelo que roda devagar', 'Erro de deploy'],
    correctIndex: 1,
    explanation: 'Model drift acontece quando a distribuição dos dados muda com o tempo, fazendo o modelo perder performance.',
  },
  {
    icon: '🚀', category: 'Futuro', difficulty: 'Médio' as const,
    text: 'O que é AGI (Artificial General Intelligence)?',
    options: ['IA específica para jogos', 'IA com capacidade cognitiva geral equivalente à humana', 'Um tipo de GPU', 'Framework de Machine Learning'],
    correctIndex: 1,
    explanation: 'AGI seria uma IA capaz de realizar qualquer tarefa intelectual humana. Ainda é um objetivo teórico e não foi alcançado.',
  },
];

export const INITIAL_PLAYER = {
  xp: 2800,
  streak: 3,
  level: 29,
  levelTitle: 'Data Analyst',
  currentXp: 2800,
  nextLevelXp: 4500,
  completedLessons: [] as number[],
};
