import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 'section-1',
    label: 'Seção 1 · Unidade 1',
    title: 'Fundamentos de IA',
    unlocked: true,
    lessons: [
      {
        icon: '⭐',
        title: 'O que é Inteligência Artificial?',
        description: 'Explore a história e os fundamentos da IA moderna.',
        topics: ['História da IA desde 1950', 'Diferença entre IA, ML e DL', 'Tipos de aprendizado', 'Aplicações reais no dia a dia'],
        questions: [
          { icon: '🤖', category: 'Conceitos', difficulty: 'Fácil', text: 'Qual é a definição mais precisa de Inteligência Artificial?', options: ['Robôs físicos que pensam', 'Sistemas que simulam capacidades cognitivas humanas', 'Qualquer software computacional', 'Programas de videogame'], correctIndex: 1, explanation: 'IA é o campo da ciência da computação que busca criar sistemas capazes de simular capacidades intelectuais humanas.' },
          { icon: '📅', category: 'Conceitos', difficulty: 'Fácil', text: 'Quem é considerado o "pai" da Inteligência Artificial?', options: ['Alan Turing', 'John McCarthy', 'Elon Musk', 'Marvin Minsky'], correctIndex: 1, explanation: 'John McCarthy cunhou o termo "Inteligência Artificial" em 1956, durante a Conferência de Dartmouth.' },
          { icon: '🧠', category: 'Conceitos', difficulty: 'Médio', text: 'O que diferencia Machine Learning de IA clássica (regras)?', options: ['ML é mais rápido', 'ML aprende padrões com dados sem regras explícitas', 'ML só funciona com imagens', 'ML precisa de mais código'], correctIndex: 1, explanation: 'IA clássica usa regras manuais. ML permite que o sistema aprenda padrões a partir de dados.' },
          { icon: '🔢', category: 'Conceitos', difficulty: 'Médio', text: 'O que são "dados de treinamento" em Machine Learning?', options: ['Documentação do sistema', 'Exemplos históricos usados para o modelo aprender', 'Logs de erro do servidor', 'Hiperparâmetros do modelo'], correctIndex: 1, explanation: 'Dados de treinamento são os exemplos que o modelo usa para aprender padrões.' },
          { icon: '🔍', category: 'Conceitos', difficulty: 'Fácil', text: 'O que é "Deep Learning"?', options: ['Aprendizado muito lento', 'Subárea de ML com redes neurais de múltiplas camadas', 'Treinamento feito por humanos', 'Uma linguagem de programação'], correctIndex: 1, explanation: 'Deep Learning usa redes neurais com muitas camadas. É a tecnologia por trás de LLMs como o ChatGPT.' },
          { icon: '🎯', category: 'Conceitos', difficulty: 'Médio', text: 'O que é aprendizado supervisionado?', options: ['IA que aprende sem professor', 'IA treinada com pares de entrada e saída rotulados', 'IA que aprende por tentativa e erro', 'IA que usa apenas texto'], correctIndex: 1, explanation: 'No aprendizado supervisionado, o modelo recebe exemplos rotulados.' },
          { icon: '💡', category: 'Conceitos', difficulty: 'Difícil', text: 'O que é "Transfer Learning"?', options: ['Transferir dados entre servidores', 'Usar conhecimento de um modelo pré-treinado em nova tarefa', 'Copiar pesos entre projetos', 'Migrar entre cloud providers'], correctIndex: 1, explanation: 'Transfer Learning reutiliza um modelo treinado e o adapta para outra tarefa.' },
          { icon: '⚖️', category: 'Ética', difficulty: 'Médio', text: 'O que é "viés algorítmico" em IA?', options: ['IA que prefere Python a JavaScript', 'Discriminação sistemática resultante de dados tendenciosos', 'Bug de cálculo matemático', 'Alta taxa de erro aleatório'], correctIndex: 1, explanation: 'Viés algorítmico ocorre quando o modelo replica preconceitos presentes nos dados de treinamento.' },
        ],
      },
      {
        icon: '🧠',
        title: 'Machine Learning na Prática',
        description: 'Entenda como algoritmos aprendem com dados.',
        topics: ['Tipos de ML', 'Dados de treino e teste', 'Métricas de avaliação', 'Casos de uso reais'],
        questions: [
          { icon: '📊', category: 'ML', difficulty: 'Fácil' as const, text: 'Qual é o objetivo principal do Machine Learning?', options: ['Substituir programadores', 'Aprender padrões a partir de dados automaticamente', 'Criar interfaces bonitas', 'Acelerar a internet'], correctIndex: 1, explanation: 'ML permite que sistemas aprendam e melhorem automaticamente com experiência.' },
          { icon: '🔢', category: 'ML', difficulty: 'Médio' as const, text: 'O que é um dataset de teste?', options: ['Dados usados para treinar', 'Dados reservados para avaliar o modelo', 'Dados descartados', 'Dados duplicados'], correctIndex: 1, explanation: 'O dataset de teste avalia quão bem o modelo generaliza para dados novos.' },
          { icon: '📈', category: 'ML', difficulty: 'Médio' as const, text: 'O que é acurácia em ML?', options: ['Velocidade do modelo', 'Porcentagem de previsões corretas', 'Tamanho do dataset', 'Número de parâmetros'], correctIndex: 1, explanation: 'Acurácia mede a proporção de previsões corretas sobre o total.' },
          { icon: '🔄', category: 'ML', difficulty: 'Médio' as const, text: 'O que é validação cruzada (cross-validation)?', options: ['Validar dados manualmente', 'Dividir dados em partes e treinar/testar múltiplas vezes', 'Comparar dois modelos', 'Verificar erros de código'], correctIndex: 1, explanation: 'Cross-validation divide os dados em k partes e alterna entre treino e teste para avaliação robusta.' },
          { icon: '⚡', category: 'ML', difficulty: 'Fácil' as const, text: 'O que é classificação em ML?', options: ['Organizar arquivos', 'Prever a categoria de um dado', 'Comprimir dados', 'Ordenar números'], correctIndex: 1, explanation: 'Classificação é prever a qual categoria um dado pertence, como spam ou não-spam.' },
          { icon: '📉', category: 'ML', difficulty: 'Médio' as const, text: 'O que é regressão em ML?', options: ['Voltar a uma versão anterior', 'Prever um valor numérico contínuo', 'Agrupar dados similares', 'Remover outliers'], correctIndex: 1, explanation: 'Regressão prevê valores contínuos, como preço de imóveis ou temperatura.' },
          { icon: '🎯', category: 'ML', difficulty: 'Difícil' as const, text: 'O que é regularização em ML?', options: ['Padronizar código', 'Técnica para evitar overfitting penalizando complexidade', 'Aumentar o dataset', 'Normalizar dados'], correctIndex: 1, explanation: 'Regularização adiciona penalidades ao modelo para evitar que ele se ajuste demais aos dados de treino.' },
          { icon: '🧪', category: 'ML', difficulty: 'Difícil' as const, text: 'O que é a matriz de confusão?', options: ['Tabela de erros de código', 'Tabela que mostra acertos e erros por classe', 'Gráfico de dispersão', 'Diagrama de fluxo'], correctIndex: 1, explanation: 'A matriz de confusão mostra verdadeiros positivos, falsos positivos, verdadeiros negativos e falsos negativos.' },
        ],
      },
      {
        icon: '💬',
        title: 'Processamento de Linguagem Natural',
        description: 'Como a IA entende e gera texto humano.',
        topics: ['Tokenização', 'Embeddings', 'Modelos de linguagem', 'Chatbots e assistentes'],
        questions: [
          { icon: '💬', category: 'NLP', difficulty: 'Fácil' as const, text: 'O que é NLP (Processamento de Linguagem Natural)?', options: ['Linguagem de programação', 'Campo da IA que trabalha com linguagem humana', 'Protocolo de rede', 'Tipo de banco de dados'], correctIndex: 1, explanation: 'NLP permite máquinas entenderem, interpretarem e gerarem linguagem humana.' },
          { icon: '🔤', category: 'NLP', difficulty: 'Médio' as const, text: 'O que são "embeddings" em NLP?', options: ['Imagens embutidas em texto', 'Representações numéricas de palavras em vetores', 'Links dentro do texto', 'Comentários no código'], correctIndex: 1, explanation: 'Embeddings convertem palavras em vetores numéricos que capturam significado semântico.' },
          { icon: '🤖', category: 'NLP', difficulty: 'Médio' as const, text: 'O que é um LLM (Large Language Model)?', options: ['Um banco de dados grande', 'Modelo treinado em bilhões de textos para gerar linguagem', 'Uma rede social', 'Um sistema operacional'], correctIndex: 1, explanation: 'LLMs como GPT são modelos massivos treinados em enormes quantidades de texto.' },
          { icon: '✂️', category: 'NLP', difficulty: 'Fácil' as const, text: 'O que é tokenização?', options: ['Criptografia', 'Dividir texto em unidades menores (tokens)', 'Traduzir idiomas', 'Comprimir texto'], correctIndex: 1, explanation: 'Tokenização divide texto em pedaços menores para o modelo processar.' },
          { icon: '🎭', category: 'NLP', difficulty: 'Médio' as const, text: 'O que é análise de sentimento?', options: ['Medir velocidade de leitura', 'Classificar texto como positivo, negativo ou neutro', 'Contar palavras', 'Detectar idioma'], correctIndex: 1, explanation: 'Análise de sentimento identifica emoções e opiniões expressas em texto.' },
          { icon: '🔗', category: 'NLP', difficulty: 'Difícil' as const, text: 'O que é o mecanismo de "Attention"?', options: ['Filtro de spam', 'Permite o modelo focar em partes relevantes da entrada', 'Sistema de cache', 'Técnica de compressão'], correctIndex: 1, explanation: 'Attention permite que o modelo pondere a importância de cada parte da entrada.' },
          { icon: '🏗️', category: 'NLP', difficulty: 'Difícil' as const, text: 'O que é a arquitetura Transformer?', options: ['Framework JavaScript', 'Arquitetura baseada em attention para processar sequências', 'Tipo de hardware', 'Banco de dados vetorial'], correctIndex: 1, explanation: 'Transformers processam sequências em paralelo usando attention, sendo a base do GPT, BERT e outros LLMs.' },
          { icon: '📝', category: 'NLP', difficulty: 'Médio' as const, text: 'O que é NER (Named Entity Recognition)?', options: ['Reconhecimento facial', 'Identificar nomes, locais e datas em texto', 'Gerar nomes aleatórios', 'Renomear arquivos'], correctIndex: 1, explanation: 'NER identifica e classifica entidades como pessoas, organizações e locais em texto.' },
        ],
      },
      {
        icon: '⚙️',
        title: 'Prompt Engineering',
        description: 'Aprenda a se comunicar melhor com a IA.',
        topics: ['Estrutura de prompts', 'Few-shot learning', 'Chain-of-Thought', 'Técnicas avançadas'],
        questions: [
          { icon: '✍️', category: 'Prompts', difficulty: 'Fácil' as const, text: 'O que é um "prompt" em IA generativa?', options: ['Código-fonte do modelo', 'Instrução ou texto de entrada dado ao modelo', 'Uma API REST', 'O resultado gerado'], correctIndex: 1, explanation: 'O prompt é o texto que você envia ao modelo de IA para obter uma resposta.' },
          { icon: '🎯', category: 'Prompts', difficulty: 'Médio' as const, text: 'O que é "few-shot prompting"?', options: ['Dar poucos comandos', 'Incluir exemplos no prompt para guiar a resposta', 'Usar modelos pequenos', 'Treinar com poucos dados'], correctIndex: 1, explanation: 'Few-shot prompting inclui exemplos no prompt para o modelo entender o padrão esperado.' },
          { icon: '🧠', category: 'Prompts', difficulty: 'Difícil' as const, text: 'O que é "Chain-of-Thought" prompting?', options: ['Encadear vários modelos', 'Pedir ao modelo que mostre o raciocínio passo a passo', 'Usar blockchain com IA', 'Repetir o mesmo prompt'], correctIndex: 1, explanation: 'Chain-of-Thought pede ao modelo que raciocine passo a passo.' },
          { icon: '🔧', category: 'Prompts', difficulty: 'Fácil' as const, text: 'O que é "system prompt"?', options: ['Mensagem de erro', 'Instrução inicial que define o comportamento do modelo', 'Configuração de hardware', 'Log do sistema'], correctIndex: 1, explanation: 'System prompt define o papel e comportamento do modelo antes da conversa com o usuário.' },
          { icon: '🌡️', category: 'Prompts', difficulty: 'Médio' as const, text: 'O que o parâmetro "temperature" controla?', options: ['Velocidade de resposta', 'Aleatoriedade/criatividade das respostas', 'Tamanho da resposta', 'Idioma da resposta'], correctIndex: 1, explanation: 'Temperature controla a aleatoriedade: baixa = mais previsível, alta = mais criativo.' },
          { icon: '📐', category: 'Prompts', difficulty: 'Médio' as const, text: 'O que é "zero-shot prompting"?', options: ['Prompt sem texto', 'Pedir ao modelo sem dar exemplos', 'Treinar do zero', 'Prompt com zero erros'], correctIndex: 1, explanation: 'Zero-shot é quando o modelo resolve a tarefa sem exemplos, apenas com a instrução.' },
          { icon: '🔄', category: 'Prompts', difficulty: 'Difícil' as const, text: 'O que é "prompt chaining"?', options: ['Repetir prompts', 'Usar a saída de um prompt como entrada de outro', 'Traduzir prompts', 'Encriptar prompts'], correctIndex: 1, explanation: 'Prompt chaining conecta múltiplos prompts em sequência para resolver tarefas complexas.' },
          { icon: '🛡️', category: 'Prompts', difficulty: 'Difícil' as const, text: 'O que é "prompt injection"?', options: ['Injeção de SQL', 'Ataque que manipula o modelo ignorando instruções originais', 'Inserir código no prompt', 'Bug de formatação'], correctIndex: 1, explanation: 'Prompt injection é quando alguém insere instruções maliciosas para manipular o comportamento do modelo.' },
        ],
      },
      {
        icon: '🎯',
        title: 'IA no Mundo Real',
        description: 'Aplicações práticas e ética da Inteligência Artificial.',
        topics: ['IA em empresas', 'Ética e viés', 'Regulamentação', 'Futuro da IA'],
        questions: [
          { icon: '🏢', category: 'Aplicações', difficulty: 'Fácil' as const, text: 'Qual área NÃO usa IA comumente hoje?', options: ['Diagnóstico médico', 'Recomendação de conteúdo', 'Fabricação de tijolos artesanais', 'Detecção de fraudes'], correctIndex: 2, explanation: 'IA é amplamente usada em saúde, entretenimento e finanças.' },
          { icon: '⚖️', category: 'Ética', difficulty: 'Médio' as const, text: 'Por que a regulamentação de IA é importante?', options: ['Para tornar a IA mais lenta', 'Para garantir uso responsável e proteger direitos', 'Para proibir toda automação', 'Para aumentar custos'], correctIndex: 1, explanation: 'Regulamentação visa garantir que IA seja usada de forma ética e transparente.' },
          { icon: '🚀', category: 'Futuro', difficulty: 'Médio' as const, text: 'O que é "IA responsável"?', options: ['IA que funciona sem bugs', 'Desenvolvimento de IA com foco em ética, transparência e inclusão', 'IA que responde rápido', 'IA open source'], correctIndex: 1, explanation: 'IA responsável considera impactos sociais, viés, privacidade e transparência.' },
          { icon: '🏥', category: 'Aplicações', difficulty: 'Fácil' as const, text: 'Como IA é usada na saúde?', options: ['Substituindo médicos', 'Auxiliando diagnósticos e análise de exames', 'Vendendo remédios', 'Gerenciando hospitais'], correctIndex: 1, explanation: 'IA auxilia médicos na análise de imagens médicas, diagnósticos e descoberta de medicamentos.' },
          { icon: '🔒', category: 'Ética', difficulty: 'Médio' as const, text: 'O que é LGPD em relação à IA?', options: ['Framework de ML', 'Lei de proteção de dados pessoais no Brasil', 'Linguagem de programação', 'Protocolo de rede'], correctIndex: 1, explanation: 'A LGPD regula como dados pessoais são coletados e usados, impactando sistemas de IA.' },
          { icon: '🌍', category: 'Futuro', difficulty: 'Difícil' as const, text: 'O que é AGI (Inteligência Artificial Geral)?', options: ['IA para jogos', 'IA com capacidade cognitiva equivalente à humana', 'Tipo de GPU', 'Framework de ML'], correctIndex: 1, explanation: 'AGI seria uma IA capaz de qualquer tarefa intelectual humana. Ainda é teórica.' },
          { icon: '💼', category: 'Aplicações', difficulty: 'Médio' as const, text: 'O que é automação inteligente?', options: ['Robótica industrial', 'Combinar IA com automação para tarefas complexas', 'Programação automática', 'Backup automático'], correctIndex: 1, explanation: 'Automação inteligente usa IA para automatizar tarefas que requerem decisão e julgamento.' },
          { icon: '🎓', category: 'Futuro', difficulty: 'Difícil' as const, text: 'O que é "AI alignment"?', options: ['Alinhar código', 'Garantir que IA aja conforme valores e intenções humanas', 'Posicionar servidores', 'Formatar dados'], correctIndex: 1, explanation: 'AI alignment busca garantir que sistemas de IA ajam de acordo com os valores e objetivos humanos.' },
        ],
      },
    ],
  },
  {
    id: 'section-2',
    label: 'Seção 2 · Unidade 2',
    title: 'Prompting Avançado',
    unlocked: false,
    lessons: [
      {
        icon: '🏜️',
        title: 'Técnicas de Prompting',
        description: 'Domine técnicas avançadas de comunicação com IA.',
        topics: ['Role prompting', 'Delimitadores', 'Output formatting', 'Iteração de prompts'],
        questions: [
          { icon: '🎭', category: 'Prompting', difficulty: 'Fácil', text: 'O que é "role prompting"?', options: ['Dar um cargo ao programador', 'Atribuir um papel/persona ao modelo de IA', 'Criar um RPG com IA', 'Definir permissões de acesso'], correctIndex: 1, explanation: 'Role prompting define um papel para a IA, como "Aja como um professor de física".' },
          { icon: '📏', category: 'Prompting', difficulty: 'Fácil', text: 'Por que usar delimitadores em prompts?', options: ['Para decorar o texto', 'Para separar claramente instruções de conteúdo', 'Para comprimir texto', 'Para traduzir'], correctIndex: 1, explanation: 'Delimitadores como """ ou ### ajudam o modelo a distinguir partes do prompt.' },
          { icon: '📋', category: 'Prompting', difficulty: 'Médio', text: 'Como pedir output estruturado à IA?', options: ['Gritar no prompt', 'Especificar formato desejado como JSON, tabela ou lista', 'Usar apenas inglês', 'Enviar arquivo PDF'], correctIndex: 1, explanation: 'Especificar o formato de saída (JSON, markdown, tabela) melhora a qualidade da resposta.' },
          { icon: '🔄', category: 'Prompting', difficulty: 'Médio', text: 'O que é iteração de prompts?', options: ['Repetir o mesmo prompt', 'Refinar progressivamente o prompt com base nos resultados', 'Usar loops no código', 'Automatizar prompts'], correctIndex: 1, explanation: 'Iteração é o processo de ajustar e melhorar o prompt com base nas respostas obtidas.' },
          { icon: '🎯', category: 'Prompting', difficulty: 'Médio', text: 'O que é "negative prompting"?', options: ['Prompt pessimista', 'Instruir o que o modelo NÃO deve fazer', 'Prompt com erros', 'Feedback negativo'], correctIndex: 1, explanation: 'Negative prompting diz ao modelo o que evitar, melhorando a qualidade da saída.' },
          { icon: '📐', category: 'Prompting', difficulty: 'Difícil', text: 'O que é "Tree of Thoughts" (ToT)?', options: ['Diagrama de árvore', 'Técnica que explora múltiplos caminhos de raciocínio', 'Estrutura de dados', 'Organograma de IA'], correctIndex: 1, explanation: 'ToT permite ao modelo explorar diferentes linhas de raciocínio antes de escolher a melhor.' },
          { icon: '🧩', category: 'Prompting', difficulty: 'Difícil', text: 'O que é "self-consistency" em prompting?', options: ['Prompt sem contradições', 'Gerar múltiplas respostas e escolher a mais frequente', 'Verificar gramática', 'Manter mesmo estilo'], correctIndex: 1, explanation: 'Self-consistency gera várias respostas independentes e seleciona a resposta mais comum.' },
          { icon: '🔬', category: 'Prompting', difficulty: 'Difícil', text: 'O que é "meta-prompting"?', options: ['Prompt sobre metaverso', 'Usar IA para gerar ou otimizar prompts', 'Prompt com metadados', 'Análise de prompts'], correctIndex: 1, explanation: 'Meta-prompting usa a própria IA para criar, avaliar e melhorar prompts automaticamente.' },
        ],
      },
      {
        icon: '🔗',
        title: 'RAG — Retrieval Augmented Generation',
        description: 'Combine busca de dados com geração de texto.',
        topics: ['O que é RAG', 'Bancos vetoriais', 'Chunking', 'Relevância e contexto'],
        questions: [
          { icon: '📚', category: 'RAG', difficulty: 'Fácil', text: 'O que é RAG?', options: ['Linguagem de programação', 'Técnica que combina busca de informação com geração de texto', 'Rede neural especial', 'Framework web'], correctIndex: 1, explanation: 'RAG busca informações relevantes em uma base de dados e usa como contexto para o modelo gerar respostas.' },
          { icon: '🗄️', category: 'RAG', difficulty: 'Médio', text: 'O que é um banco de dados vetorial?', options: ['Banco com imagens', 'Banco que armazena e busca por similaridade de vetores', 'Banco de dados gráfico', 'Banco relacional'], correctIndex: 1, explanation: 'Bancos vetoriais como Pinecone e Weaviate armazenam embeddings e permitem busca por similaridade.' },
          { icon: '✂️', category: 'RAG', difficulty: 'Médio', text: 'O que é "chunking" em RAG?', options: ['Comprimir dados', 'Dividir documentos em pedaços menores para indexação', 'Agrupar queries', 'Fragmentar rede neural'], correctIndex: 1, explanation: 'Chunking divide documentos grandes em partes menores para indexação e busca eficientes.' },
          { icon: '🎯', category: 'RAG', difficulty: 'Médio', text: 'Por que RAG reduz alucinações?', options: ['Usa mais GPU', 'Fornece contexto real e atualizado ao modelo', 'Treina mais devagar', 'Remove palavras difíceis'], correctIndex: 1, explanation: 'RAG dá ao modelo informações factuais para basear suas respostas, reduzindo invenções.' },
          { icon: '🔍', category: 'RAG', difficulty: 'Difícil', text: 'O que é "hybrid search" em RAG?', options: ['Busca em dois idiomas', 'Combinar busca semântica com busca por palavras-chave', 'Buscar em dois bancos', 'Busca com dois modelos'], correctIndex: 1, explanation: 'Hybrid search combina busca vetorial (semântica) com busca lexical (BM25) para melhor relevância.' },
          { icon: '📊', category: 'RAG', difficulty: 'Difícil', text: 'O que é "reranking" em RAG?', options: ['Reorganizar código', 'Reordenar resultados de busca por relevância usando outro modelo', 'Ranking de modelos', 'Classificar dados'], correctIndex: 1, explanation: 'Reranking usa um modelo de cross-encoder para reordenar os chunks mais relevantes.' },
          { icon: '🧩', category: 'RAG', difficulty: 'Médio', text: 'Qual ferramenta é popular para construir pipelines RAG?', options: ['React', 'LangChain', 'Docker', 'PostgreSQL'], correctIndex: 1, explanation: 'LangChain é um framework popular para construir aplicações com LLMs incluindo pipelines RAG.' },
          { icon: '⚡', category: 'RAG', difficulty: 'Fácil', text: 'Qual vantagem do RAG sobre fine-tuning?', options: ['É mais lento', 'Não precisa retreinar o modelo para atualizar conhecimento', 'Usa mais dados', 'É mais caro'], correctIndex: 1, explanation: 'RAG permite atualizar o conhecimento apenas atualizando a base de dados, sem retreinar o modelo.' },
        ],
      },
      {
        icon: '🤖',
        title: 'Agentes de IA',
        description: 'IA que toma decisões e executa ações autonomamente.',
        topics: ['O que são agentes', 'Ferramentas e funções', 'Planejamento', 'Multi-agentes'],
        questions: [
          { icon: '🤖', category: 'Agentes', difficulty: 'Fácil', text: 'O que é um agente de IA?', options: ['Um chatbot simples', 'Sistema de IA que pode raciocinar, planejar e executar ações', 'Um robô físico', 'Um antivírus'], correctIndex: 1, explanation: 'Agentes de IA combinam raciocínio com ação, podendo usar ferramentas e tomar decisões.' },
          { icon: '🔧', category: 'Agentes', difficulty: 'Médio', text: 'O que é "function calling" em LLMs?', options: ['Chamar funções JavaScript', 'Capacidade do modelo de invocar ferramentas externas', 'Programação funcional', 'Debugging'], correctIndex: 1, explanation: 'Function calling permite que o modelo decida quando e como usar ferramentas externas (APIs, cálculos, etc).' },
          { icon: '📋', category: 'Agentes', difficulty: 'Médio', text: 'O que é o padrão ReAct em agentes?', options: ['Framework React', 'Alternar entre raciocínio (Reason) e ação (Act)', 'Reação química', 'Reactive programming'], correctIndex: 1, explanation: 'ReAct combina raciocínio e ação: o agente pensa, age, observa e repete até resolver o problema.' },
          { icon: '🌐', category: 'Agentes', difficulty: 'Difícil', text: 'O que são sistemas multi-agentes?', options: ['Muitos chatbots', 'Múltiplos agentes colaborando para resolver tarefas complexas', 'Rede distribuída', 'Cluster de GPUs'], correctIndex: 1, explanation: 'Sistemas multi-agentes têm agentes especializados que colaboram, como pesquisador + escritor + revisor.' },
          { icon: '🧠', category: 'Agentes', difficulty: 'Médio', text: 'O que é "memory" em agentes de IA?', options: ['RAM do servidor', 'Capacidade do agente de lembrar interações anteriores', 'Backup de dados', 'Cache do browser'], correctIndex: 1, explanation: 'Memória permite que agentes mantenham contexto entre interações, melhorando a continuidade.' },
          { icon: '🛡️', category: 'Agentes', difficulty: 'Difícil', text: 'O que é "guardrails" em agentes?', options: ['Proteção física', 'Limites e regras de segurança para controlar o agente', 'Firewall', 'Antivírus de IA'], correctIndex: 1, explanation: 'Guardrails são restrições que impedem o agente de tomar ações perigosas ou fora do escopo.' },
          { icon: '🔄', category: 'Agentes', difficulty: 'Difícil', text: 'O que é "tool use" em agentes?', options: ['Usar IDE', 'Capacidade de selecionar e usar ferramentas para completar tarefas', 'Instalar software', 'Configurar ambiente'], correctIndex: 1, explanation: 'Tool use permite que o agente escolha entre ferramentas disponíveis (busca, código, API) conforme necessário.' },
          { icon: '📊', category: 'Agentes', difficulty: 'Fácil', text: 'Qual é um exemplo real de agente de IA?', options: ['Calculadora', 'Assistente que pesquisa, analisa dados e gera relatórios', 'Editor de texto', 'Navegador web'], correctIndex: 1, explanation: 'Agentes como AutoGPT e Devin podem planejar e executar tarefas complexas de forma autônoma.' },
        ],
      },
      {
        icon: '🧪',
        title: 'Fine-tuning e Customização',
        description: 'Personalize modelos de IA para suas necessidades.',
        topics: ['Fine-tuning vs prompting', 'Preparação de dados', 'LoRA e QLoRA', 'Avaliação'],
        questions: [
          { icon: '🔧', category: 'Fine-tuning', difficulty: 'Fácil', text: 'O que é fine-tuning de um modelo?', options: ['Ajustar hardware', 'Retreinar um modelo pré-treinado com dados específicos', 'Instalar plugins', 'Configurar parâmetros de rede'], correctIndex: 1, explanation: 'Fine-tuning adapta um modelo existente com dados específicos do seu domínio ou tarefa.' },
          { icon: '📊', category: 'Fine-tuning', difficulty: 'Médio', text: 'Quando usar fine-tuning em vez de prompting?', options: ['Sempre', 'Quando precisa de consistência alta em tarefas específicas', 'Nunca', 'Quando o custo não importa'], correctIndex: 1, explanation: 'Fine-tuning é ideal quando prompting não alcança a qualidade necessária para tarefas repetitivas.' },
          { icon: '🧬', category: 'Fine-tuning', difficulty: 'Difícil', text: 'O que é LoRA (Low-Rank Adaptation)?', options: ['Protocolo de rede', 'Técnica eficiente de fine-tuning que treina poucos parâmetros', 'Linguagem de programação', 'Tipo de GPU'], correctIndex: 1, explanation: 'LoRA treina apenas matrizes de baixo rank, reduzindo drasticamente custo e memória necessários.' },
          { icon: '💾', category: 'Fine-tuning', difficulty: 'Médio', text: 'Como preparar dados para fine-tuning?', options: ['Copiar da internet', 'Criar pares de instrução-resposta no formato do modelo', 'Usar dados aleatórios', 'Gerar dados com IA'], correctIndex: 1, explanation: 'Dados de fine-tuning devem ser pares curados de input-output que representem a tarefa desejada.' },
          { icon: '⚖️', category: 'Fine-tuning', difficulty: 'Médio', text: 'O que é "catastrophic forgetting"?', options: ['Bug de memória', 'Modelo esquecer conhecimento anterior ao aprender algo novo', 'Perda de dados', 'Crash do sistema'], correctIndex: 1, explanation: 'Fine-tuning agressivo pode fazer o modelo esquecer capacidades gerais ao se especializar demais.' },
          { icon: '📈', category: 'Fine-tuning', difficulty: 'Difícil', text: 'O que é QLoRA?', options: ['Query Language', 'LoRA combinado com quantização para usar menos memória', 'Quantum LoRA', 'Quality LoRA'], correctIndex: 1, explanation: 'QLoRA combina quantização de 4-bit com LoRA, permitindo fine-tuning em GPUs com pouca memória.' },
          { icon: '🧪', category: 'Fine-tuning', difficulty: 'Fácil', text: 'Qual plataforma facilita fine-tuning?', options: ['Word', 'OpenAI API, Hugging Face ou Replicate', 'Instagram', 'Spotify'], correctIndex: 1, explanation: 'Plataformas como OpenAI API e Hugging Face oferecem ferramentas simplificadas para fine-tuning.' },
          { icon: '📏', category: 'Fine-tuning', difficulty: 'Difícil', text: 'Como avaliar um modelo fine-tunado?', options: ['Apenas pela acurácia', 'Usando métricas específicas da tarefa e testes humanos', 'Pelo tamanho do modelo', 'Pelo custo de treino'], correctIndex: 1, explanation: 'Avaliação combina métricas automáticas (BLEU, ROUGE) com avaliação humana qualitativa.' },
        ],
      },
      {
        icon: '🎓',
        title: 'Avaliação e Métricas de LLMs',
        description: 'Como medir a qualidade de modelos de linguagem.',
        topics: ['Benchmarks', 'Métricas de qualidade', 'Alucinações', 'Testes A/B'],
        questions: [
          { icon: '📊', category: 'Avaliação', difficulty: 'Fácil', text: 'O que é uma "alucinação" em LLMs?', options: ['Bug visual', 'Quando o modelo gera informação falsa com confiança', 'Efeito de GPU', 'Texto corrompido'], correctIndex: 1, explanation: 'Alucinação é quando o modelo inventa fatos que parecem verdadeiros mas são incorretos.' },
          { icon: '📏', category: 'Avaliação', difficulty: 'Médio', text: 'O que é o benchmark MMLU?', options: ['Tipo de modelo', 'Teste que avalia conhecimento em 57 áreas do saber', 'Framework de treino', 'Métrica de velocidade'], correctIndex: 1, explanation: 'MMLU testa modelos em questões de múltipla escolha de 57 áreas, do direito à medicina.' },
          { icon: '🎯', category: 'Avaliação', difficulty: 'Médio', text: 'O que é "perplexity" em LLMs?', options: ['Confusão do usuário', 'Métrica que mede quão bem o modelo prevê o próximo token', 'Complexidade do código', 'Nível de dificuldade'], correctIndex: 1, explanation: 'Perplexity mede a incerteza do modelo: menor perplexity = melhor capacidade de prever texto.' },
          { icon: '🔍', category: 'Avaliação', difficulty: 'Fácil', text: 'Como detectar alucinações?', options: ['Impossível detectar', 'Verificar fontes, usar RAG e avaliação humana', 'Ignorar todas as respostas', 'Usar modelos menores'], correctIndex: 1, explanation: 'Combinar verificação de fontes, RAG para fundamentação e revisão humana reduz alucinações.' },
          { icon: '⚡', category: 'Avaliação', difficulty: 'Médio', text: 'O que é latência em LLMs?', options: ['Atraso de rede', 'Tempo entre enviar prompt e receber resposta completa', 'Custo por token', 'Tamanho do modelo'], correctIndex: 1, explanation: 'Latência é o tempo de resposta do modelo, crucial para experiência do usuário em tempo real.' },
          { icon: '💰', category: 'Avaliação', difficulty: 'Fácil', text: 'O que são "tokens" em termos de custo?', options: ['Criptomoedas', 'Unidades de texto que determinam o preço das APIs de IA', 'Pontos de fidelidade', 'Vouchers'], correctIndex: 1, explanation: 'APIs de LLM cobram por token processado (input + output). Cada palavra tem ~1-3 tokens.' },
          { icon: '🧪', category: 'Avaliação', difficulty: 'Difícil', text: 'O que é "LLM-as-a-Judge"?', options: ['IA no tribunal', 'Usar um LLM para avaliar outputs de outro LLM', 'Modelo jurídico', 'Juiz artificial'], correctIndex: 1, explanation: 'LLM-as-a-Judge usa modelos potentes (como GPT-4) para avaliar a qualidade de respostas de outros modelos.' },
          { icon: '📈', category: 'Avaliação', difficulty: 'Difícil', text: 'O que é "ELO rating" para LLMs?', options: ['Ranking de xadrez', 'Sistema de classificação baseado em comparações diretas entre modelos', 'Nota de escola', 'Tipo de benchmark'], correctIndex: 1, explanation: 'Chatbot Arena usa ELO rating para classificar LLMs com base em preferências humanas em comparações cegas.' },
        ],
      },
    ],
  },
  {
    id: 'section-3',
    label: 'Seção 3 · Unidade 3',
    title: 'IA Generativa',
    unlocked: false,
    lessons: [
      {
        icon: '🎨',
        title: 'Geração de Imagens com IA',
        description: 'De DALL-E a Midjourney — como IA cria arte.',
        topics: ['Diffusion models', 'Text-to-image', 'Estilos e controle', 'Ética visual'],
        questions: [
          { icon: '🎨', category: 'Imagens', difficulty: 'Fácil', text: 'O que é DALL-E?', options: ['Editor de fotos', 'Modelo de IA que gera imagens a partir de texto', 'Rede social', 'Plugin do Photoshop'], correctIndex: 1, explanation: 'DALL-E é um modelo da OpenAI que cria imagens originais a partir de descrições textuais.' },
          { icon: '🌀', category: 'Imagens', difficulty: 'Médio', text: 'O que são "diffusion models"?', options: ['Modelos que difundem informação', 'Modelos que aprendem a remover ruído para gerar imagens', 'Filtros de imagem', 'Modelos de propagação'], correctIndex: 1, explanation: 'Diffusion models aprendem a desruidar imagens, gerando novas imagens de alta qualidade no processo.' },
          { icon: '✏️', category: 'Imagens', difficulty: 'Fácil', text: 'O que é Midjourney?', options: ['Jogo de RPG', 'Ferramenta de IA para gerar arte a partir de prompts', 'Editor de vídeo', 'Rede social de artistas'], correctIndex: 1, explanation: 'Midjourney é um serviço de IA generativa focado em criar imagens artísticas de alta qualidade.' },
          { icon: '🔧', category: 'Imagens', difficulty: 'Médio', text: 'O que é "img2img" em IA generativa?', options: ['Converter formato de imagem', 'Gerar uma nova imagem baseada em outra imagem existente', 'Comparar duas imagens', 'Duplicar imagem'], correctIndex: 1, explanation: 'Img2img usa uma imagem como base e a transforma segundo um prompt, mantendo estrutura similar.' },
          { icon: '🎭', category: 'Imagens', difficulty: 'Médio', text: 'O que é "ControlNet"?', options: ['Firewall', 'Técnica para controlar composição e pose na geração de imagens', 'Rede de controle', 'Gerenciador de rede'], correctIndex: 1, explanation: 'ControlNet permite controlar aspectos como pose, bordas e profundidade na geração de imagens.' },
          { icon: '⚖️', category: 'Imagens', difficulty: 'Difícil', text: 'Qual é a principal questão ética em IA de imagens?', options: ['Custo de GPU', 'Direitos autorais de obras usadas no treinamento', 'Velocidade de geração', 'Resolução das imagens'], correctIndex: 1, explanation: 'Modelos treinados com obras de artistas sem permissão levantam questões sérias sobre direitos autorais.' },
          { icon: '📐', category: 'Imagens', difficulty: 'Difícil', text: 'O que é "latent space" em diffusion models?', options: ['Espaço de armazenamento', 'Representação comprimida onde o modelo opera', 'Espaço físico do servidor', 'Área de memória'], correctIndex: 1, explanation: 'O espaço latente é uma representação matemática comprimida onde o modelo processa e gera imagens mais eficientemente.' },
          { icon: '🖼️', category: 'Imagens', difficulty: 'Fácil', text: 'O que é Stable Diffusion?', options: ['Protocolo de rede', 'Modelo de código aberto para gerar imagens com IA', 'Estabilizador de vídeo', 'Formato de arquivo'], correctIndex: 1, explanation: 'Stable Diffusion é um modelo open-source popular para geração de imagens, rodável localmente.' },
        ],
      },
      {
        icon: '🎵',
        title: 'IA para Áudio e Música',
        description: 'Geração de voz, música e efeitos sonoros com IA.',
        topics: ['Text-to-speech', 'Clonagem de voz', 'Geração de música', 'Audio AI'],
        questions: [
          { icon: '🗣️', category: 'Áudio', difficulty: 'Fácil', text: 'O que é TTS (Text-to-Speech)?', options: ['Tipo de arquivo', 'Tecnologia que converte texto em fala natural', 'Protocolo de rede', 'Editor de áudio'], correctIndex: 1, explanation: 'TTS usa IA para transformar texto escrito em fala natural, como vozes do Google e ElevenLabs.' },
          { icon: '🎙️', category: 'Áudio', difficulty: 'Médio', text: 'O que é clonagem de voz com IA?', options: ['Gravar voz', 'Criar uma voz sintética que soa como uma pessoa real', 'Editar áudio', 'Transcrever áudio'], correctIndex: 1, explanation: 'Clonagem de voz replica as características vocais de uma pessoa com apenas segundos de áudio.' },
          { icon: '🎵', category: 'Áudio', difficulty: 'Fácil', text: 'O que é Suno AI?', options: ['Editor de vídeo', 'Plataforma que gera músicas completas com IA', 'Rede social', 'Plugin de mixagem'], correctIndex: 1, explanation: 'Suno gera músicas completas com voz, instrumentos e letra a partir de um prompt de texto.' },
          { icon: '🔊', category: 'Áudio', difficulty: 'Médio', text: 'O que é Whisper da OpenAI?', options: ['Chatbot', 'Modelo de IA para transcrição de áudio em texto', 'Assistente virtual', 'Rede social'], correctIndex: 1, explanation: 'Whisper é um modelo de reconhecimento de fala que transcreve áudio em texto com alta precisão.' },
          { icon: '🎼', category: 'Áudio', difficulty: 'Médio', text: 'Como IA compõe música?', options: ['Copia músicas existentes', 'Aprende padrões musicais e gera novas composições', 'Usa MIDI aleatório', 'Mistura faixas prontas'], correctIndex: 1, explanation: 'Modelos aprendem estruturas musicais (harmonia, ritmo, melodia) e geram composições originais.' },
          { icon: '⚠️', category: 'Áudio', difficulty: 'Difícil', text: 'O que são "deepfake" de áudio?', options: ['Música eletrônica', 'Áudios falsos que imitam a voz de pessoas reais', 'Efeitos sonoros', 'Compressão de áudio'], correctIndex: 1, explanation: 'Deepfakes de áudio usam IA para criar gravações falsas convincentes, levantando preocupações éticas.' },
          { icon: '🎹', category: 'Áudio', difficulty: 'Difícil', text: 'O que é MusicLM do Google?', options: ['Playlist automática', 'Modelo que gera música a partir de descrições textuais detalhadas', 'Serviço de streaming', 'Editor MIDI'], correctIndex: 1, explanation: 'MusicLM gera músicas de alta qualidade a partir de prompts textuais descrevendo gênero, instrumentos e mood.' },
          { icon: '🔉', category: 'Áudio', difficulty: 'Fácil', text: 'O que é "noise cancellation" com IA?', options: ['Silenciar microfone', 'Usar IA para remover ruídos de fundo em tempo real', 'Abafar som fisicamente', 'Baixar volume'], correctIndex: 1, explanation: 'IA identifica e remove ruídos de fundo (vento, digitação, etc) preservando a voz principal.' },
        ],
      },
      {
        icon: '🎬',
        title: 'Geração de Vídeo com IA',
        description: 'De Sora a Runway — o futuro do vídeo com IA.',
        topics: ['Text-to-video', 'Edição por IA', 'Deepfakes', 'Ferramentas'],
        questions: [
          { icon: '🎬', category: 'Vídeo', difficulty: 'Fácil', text: 'O que é Sora da OpenAI?', options: ['Editor de texto', 'Modelo que gera vídeos realistas a partir de texto', 'Rede social', 'App de câmera'], correctIndex: 1, explanation: 'Sora é um modelo de IA que gera vídeos fotorrealistas a partir de descrições textuais.' },
          { icon: '🎞️', category: 'Vídeo', difficulty: 'Fácil', text: 'O que é Runway ML?', options: ['Pista de aeroporto', 'Plataforma de ferramentas de IA para criação de vídeo', 'Framework web', 'Editor de código'], correctIndex: 1, explanation: 'Runway oferece ferramentas de IA para gerar, editar e transformar vídeos.' },
          { icon: '🔄', category: 'Vídeo', difficulty: 'Médio', text: 'O que é "inpainting" em vídeo com IA?', options: ['Pintar quadros', 'Preencher ou remover objetos em vídeos automaticamente', 'Adicionar filtros', 'Comprimir vídeo'], correctIndex: 1, explanation: 'Inpainting usa IA para remover ou adicionar elementos em vídeos de forma natural e consistente.' },
          { icon: '😱', category: 'Vídeo', difficulty: 'Médio', text: 'O que é um deepfake de vídeo?', options: ['Vídeo em 4K', 'Vídeo manipulado com IA para trocar rostos ou criar cenas falsas', 'Efeito especial tradicional', 'Vídeo acelerado'], correctIndex: 1, explanation: 'Deepfakes de vídeo usam IA para substituir rostos ou criar vídeos falsos convincentes.' },
          { icon: '🎭', category: 'Vídeo', difficulty: 'Difícil', text: 'O que é "motion capture" com IA?', options: ['Capturar tela', 'Extrair movimentos humanos de vídeos sem sensores especiais', 'Gravar gameplay', 'Capturar áudio'], correctIndex: 1, explanation: 'IA pode extrair movimentos corporais de vídeos comuns, sem necessidade de trajes com sensores.' },
          { icon: '🎨', category: 'Vídeo', difficulty: 'Médio', text: 'O que é "style transfer" em vídeo?', options: ['Mudar formato', 'Aplicar o estilo visual de uma obra de arte a um vídeo', 'Transferir arquivo', 'Converter codec'], correctIndex: 1, explanation: 'Style transfer aplica o estilo artístico de uma imagem (como Van Gogh) a cada frame de um vídeo.' },
          { icon: '📹', category: 'Vídeo', difficulty: 'Difícil', text: 'O que é "temporal consistency" em vídeo AI?', options: ['Sincronização de áudio', 'Manter coerência visual entre frames consecutivos', 'Compressão temporal', 'Duração do vídeo'], correctIndex: 1, explanation: 'Consistência temporal garante que elementos não "pisquem" ou mudem aleatoriamente entre frames.' },
          { icon: '🔮', category: 'Vídeo', difficulty: 'Difícil', text: 'O que é "video upscaling" com IA?', options: ['Aumentar volume', 'Aumentar resolução de vídeos com IA preservando detalhes', 'Upload de vídeo', 'Acelerar vídeo'], correctIndex: 1, explanation: 'IA pode aumentar resolução de vídeos (ex: 480p → 4K) recriando detalhes que não existiam no original.' },
        ],
      },
      {
        icon: '💻',
        title: 'IA para Código',
        description: 'Assistentes de código e desenvolvimento com IA.',
        topics: ['GitHub Copilot', 'Cursor', 'Code review', 'Debugging com IA'],
        questions: [
          { icon: '💻', category: 'Código', difficulty: 'Fácil', text: 'O que é GitHub Copilot?', options: ['Versão premium do GitHub', 'Assistente de IA que sugere código em tempo real', 'Browser para programadores', 'App de chat'], correctIndex: 1, explanation: 'Copilot usa IA para sugerir código, completar funções e ajudar no desenvolvimento em tempo real.' },
          { icon: '🖥️', category: 'Código', difficulty: 'Fácil', text: 'O que é Cursor?', options: ['Ponteiro do mouse', 'Editor de código com IA integrada nativamente', 'Terminal', 'Navegador'], correctIndex: 1, explanation: 'Cursor é um editor de código baseado em VS Code com IA profundamente integrada para edição e geração de código.' },
          { icon: '🔍', category: 'Código', difficulty: 'Médio', text: 'Como IA ajuda em code review?', options: ['Substituindo revisores', 'Identificando bugs, vulnerabilidades e sugerindo melhorias', 'Formatando código', 'Contando linhas'], correctIndex: 1, explanation: 'IA pode analisar código, encontrar bugs potenciais, sugerir otimizações e verificar segurança.' },
          { icon: '🐛', category: 'Código', difficulty: 'Médio', text: 'Como IA ajuda no debugging?', options: ['Ignorando erros', 'Analisando stack traces e sugerindo correções', 'Deletando bugs', 'Reinstalando tudo'], correctIndex: 1, explanation: 'IA pode interpretar mensagens de erro, analisar contexto e sugerir correções específicas.' },
          { icon: '🧪', category: 'Código', difficulty: 'Médio', text: 'IA pode escrever testes automatizados?', options: ['Não, é impossível', 'Sim, gerando testes unitários e de integração', 'Só testes manuais', 'Apenas em Python'], correctIndex: 1, explanation: 'IA pode gerar testes unitários, de integração e até testes E2E baseados no código existente.' },
          { icon: '📝', category: 'Código', difficulty: 'Fácil', text: 'IA pode gerar documentação de código?', options: ['Nunca', 'Sim, criando docstrings, READMEs e comentários', 'Só em inglês', 'Apenas PDFs'], correctIndex: 1, explanation: 'IA gera documentação automaticamente analisando o código e descrevendo funcionalidades.' },
          { icon: '🔒', category: 'Código', difficulty: 'Difícil', text: 'Qual risco de usar código gerado por IA?', options: ['Código muito rápido', 'Pode conter vulnerabilidades de segurança não detectadas', 'Código muito documentado', 'Código muito curto'], correctIndex: 1, explanation: 'Código gerado por IA pode ter vulnerabilidades sutis que passam despercebidas se não revisado.' },
          { icon: '🚀', category: 'Código', difficulty: 'Difícil', text: 'O que é "agentic coding"?', options: ['Programar em agência', 'IA que planeja, implementa e testa código autonomamente', 'Código de agente secreto', 'Pair programming'], correctIndex: 1, explanation: 'Agentic coding é quando a IA atua como desenvolvedor autônomo, planejando e executando tarefas de programação.' },
        ],
      },
      {
        icon: '🌐',
        title: 'Modelos Multimodais',
        description: 'IA que entende texto, imagem, áudio e vídeo simultaneamente.',
        topics: ['GPT-4V', 'Gemini', 'Claude Vision', 'Aplicações multimodais'],
        questions: [
          { icon: '🌐', category: 'Multimodal', difficulty: 'Fácil', text: 'O que é um modelo multimodal?', options: ['Modelo com vários modos', 'IA que processa múltiplos tipos de dados (texto, imagem, áudio)', 'Modelo com várias versões', 'IA multilíngue'], correctIndex: 1, explanation: 'Modelos multimodais entendem e geram conteúdo em múltiplas modalidades simultaneamente.' },
          { icon: '👁️', category: 'Multimodal', difficulty: 'Fácil', text: 'O que GPT-4V pode fazer com imagens?', options: ['Só gerar imagens', 'Analisar, descrever e responder perguntas sobre imagens', 'Só comprimir imagens', 'Só editar fotos'], correctIndex: 1, explanation: 'GPT-4V pode ver e entender imagens, descrevê-las, responder perguntas e até ler texto nelas.' },
          { icon: '🔮', category: 'Multimodal', difficulty: 'Médio', text: 'O que é Gemini do Google?', options: ['Signo do zodíaco', 'Modelo multimodal que processa texto, código, imagem e áudio', 'Navegador web', 'Sistema operacional'], correctIndex: 1, explanation: 'Gemini é a família de modelos multimodais do Google, capaz de processar texto, imagem, áudio e código.' },
          { icon: '📸', category: 'Multimodal', difficulty: 'Médio', text: 'O que é OCR com IA?', options: ['Formato de imagem', 'Reconhecimento de texto em imagens usando IA avançada', 'Compressão de foto', 'Filtro de câmera'], correctIndex: 1, explanation: 'OCR com IA vai além do OCR tradicional, entendendo layout, tabelas e contexto do texto em imagens.' },
          { icon: '🎤', category: 'Multimodal', difficulty: 'Médio', text: 'O que é o modo de voz do ChatGPT?', options: ['Podcast automático', 'Conversar com IA por voz em tempo real com tom natural', 'Gravador de voz', 'Radio online'], correctIndex: 1, explanation: 'O modo de voz permite conversas faladas naturais com a IA, incluindo emoções e entonação.' },
          { icon: '🔄', category: 'Multimodal', difficulty: 'Difícil', text: 'O que é "cross-modal understanding"?', options: ['Entender dois idiomas', 'Capacidade de relacionar informações entre diferentes tipos de mídia', 'Converter formatos', 'Traduzir imagem em texto'], correctIndex: 1, explanation: 'É a capacidade de um modelo conectar conceitos entre modalidades, como relacionar uma imagem a texto sobre ela.' },
          { icon: '🏗️', category: 'Multimodal', difficulty: 'Difícil', text: 'O que é "visual grounding"?', options: ['Paisagismo', 'Conectar palavras de um texto a regiões específicas de uma imagem', 'Edição de foto', 'Estabilizar imagem'], correctIndex: 1, explanation: 'Visual grounding localiza na imagem exatamente o que é mencionado no texto.' },
          { icon: '🚀', category: 'Multimodal', difficulty: 'Difícil', text: 'Qual é o futuro dos modelos multimodais?', options: ['Serão descontinuados', 'Integração de todos os sentidos: visão, áudio, toque e até olfato', 'Voltarão a ser só texto', 'Serão apenas para empresas'], correctIndex: 1, explanation: 'A tendência é modelos cada vez mais unificados, processando qualquer tipo de input de forma integrada.' },
        ],
      },
    ],
  },
  {
    id: 'section-4',
    label: 'Seção 4 · Unidade 4',
    title: 'IA na Prática',
    unlocked: false,
    lessons: [
      {
        icon: '🔌',
        title: 'APIs de IA',
        description: 'Integrando IA em produtos reais via APIs.',
        topics: ['OpenAI API', 'Autenticação', 'Rate limits', 'Custos e otimização'],
        questions: [
          { icon: '🔌', category: 'APIs', difficulty: 'Fácil', text: 'O que é uma API de IA?', options: ['Interface gráfica', 'Interface para acessar modelos de IA programaticamente', 'Rede social de IA', 'Tipo de modelo'], correctIndex: 1, explanation: 'APIs de IA permitem integrar modelos como GPT, Claude ou Gemini em suas aplicações via código.' },
          { icon: '🔑', category: 'APIs', difficulty: 'Fácil', text: 'O que é uma API key?', options: ['Senha do WiFi', 'Chave de autenticação para acessar uma API', 'Tipo de criptografia', 'Atalho de teclado'], correctIndex: 1, explanation: 'A API key identifica e autoriza seu aplicativo a usar os serviços da API.' },
          { icon: '💰', category: 'APIs', difficulty: 'Médio', text: 'Como funciona a cobrança das APIs de LLMs?', options: ['Mensalidade fixa', 'Por quantidade de tokens processados (input + output)', 'Por hora de uso', 'Gratuito sempre'], correctIndex: 1, explanation: 'APIs cobram por tokens: quanto mais texto processar (enviar e receber), maior o custo.' },
          { icon: '⚡', category: 'APIs', difficulty: 'Médio', text: 'O que é "streaming" em APIs de LLM?', options: ['Assistir vídeo', 'Receber a resposta token por token em tempo real', 'Transmissão ao vivo', 'Download rápido'], correctIndex: 1, explanation: 'Streaming permite ver a resposta sendo gerada em tempo real, melhorando a experiência do usuário.' },
          { icon: '🚧', category: 'APIs', difficulty: 'Médio', text: 'O que é "rate limiting" em APIs?', options: ['Avaliação de qualidade', 'Limite de requisições por período de tempo', 'Velocidade da rede', 'Pontuação do modelo'], correctIndex: 1, explanation: 'Rate limiting controla quantas chamadas à API podem ser feitas por minuto/hora para evitar abuso.' },
          { icon: '🔄', category: 'APIs', difficulty: 'Difícil', text: 'O que é "function calling" nas APIs de LLM?', options: ['Ligar para suporte', 'Permitir que o modelo invoque funções/APIs externas', 'Chamar função JavaScript', 'Recursão'], correctIndex: 1, explanation: 'Function calling permite que o LLM decida usar ferramentas externas (buscar dados, calcular, etc).' },
          { icon: '📊', category: 'APIs', difficulty: 'Difícil', text: 'Como otimizar custos de API de IA?', options: ['Não usar', 'Usar cache, prompts menores, modelos adequados e batching', 'Usar só modelos grandes', 'Ignorar tokens'], correctIndex: 1, explanation: 'Otimizar prompts, usar cache de respostas, escolher modelo adequado e agrupar requisições reduz custos.' },
          { icon: '🛡️', category: 'APIs', difficulty: 'Médio', text: 'Por que não expor API keys no frontend?', options: ['Estética do código', 'Podem ser roubadas e usadas por outros, gerando custos', 'Não faz diferença', 'Por conveniência'], correctIndex: 1, explanation: 'API keys expostas no frontend podem ser descobertas e usadas por terceiros, gerando custos e riscos.' },
        ],
      },
      {
        icon: '⚡',
        title: 'Automações com IA',
        description: 'Automatize workflows usando IA como motor.',
        topics: ['n8n e Make', 'Workflows inteligentes', 'Triggers', 'Integrações'],
        questions: [
          { icon: '⚡', category: 'Automação', difficulty: 'Fácil', text: 'O que é automação com IA?', options: ['IA automática', 'Usar IA para automatizar tarefas e decisões em workflows', 'Robótica industrial', 'Programação automática'], correctIndex: 1, explanation: 'Automação com IA combina ferramentas de automação (como n8n) com modelos de IA para decisões inteligentes.' },
          { icon: '🔗', category: 'Automação', difficulty: 'Fácil', text: 'O que é n8n?', options: ['Linguagem de programação', 'Plataforma de automação de workflows com interface visual', 'Rede social', 'Banco de dados'], correctIndex: 1, explanation: 'n8n permite criar automações conectando diferentes serviços e APIs através de uma interface visual.' },
          { icon: '🎯', category: 'Automação', difficulty: 'Médio', text: 'O que é um "trigger" em automação?', options: ['Botão de disparo', 'Evento que inicia automaticamente um workflow', 'Filtro de dados', 'Condição de parada'], correctIndex: 1, explanation: 'Triggers são eventos (novo email, webhook, agendamento) que iniciam a execução de um workflow.' },
          { icon: '📧', category: 'Automação', difficulty: 'Médio', text: 'Como IA pode automatizar respostas de email?', options: ['Deletando emails', 'Classificando, resumindo e gerando respostas personalizadas', 'Bloqueando spam', 'Encaminhando tudo'], correctIndex: 1, explanation: 'IA pode ler emails, classificar por urgência, resumir conteúdo e redigir respostas adequadas.' },
          { icon: '📊', category: 'Automação', difficulty: 'Médio', text: 'O que é um webhook?', options: ['Site malicioso', 'URL que recebe dados automaticamente quando um evento ocorre', 'Tipo de cache', 'Plugin do browser'], correctIndex: 1, explanation: 'Webhooks enviam dados automaticamente para sua aplicação quando eventos acontecem em outros serviços.' },
          { icon: '🤖', category: 'Automação', difficulty: 'Difícil', text: 'O que é RPA (Robotic Process Automation)?', options: ['Robótica física', 'Software que automatiza tarefas repetitivas imitando ações humanas', 'Renderização', 'Processamento de áudio'], correctIndex: 1, explanation: 'RPA usa bots de software para automatizar tarefas rotineiras como preencher formulários e extrair dados.' },
          { icon: '🔄', category: 'Automação', difficulty: 'Difícil', text: 'O que é "intelligent document processing"?', options: ['Imprimir documentos', 'Usar IA para extrair e classificar informações de documentos', 'Editar PDFs', 'Converter formatos'], correctIndex: 1, explanation: 'IDP usa IA para ler, entender e extrair dados estruturados de documentos como faturas, contratos e formulários.' },
          { icon: '📈', category: 'Automação', difficulty: 'Fácil', text: 'Qual benefício principal da automação com IA?', options: ['Gastar mais tempo', 'Reduzir trabalho manual e aumentar eficiência', 'Complicar processos', 'Aumentar custos'], correctIndex: 1, explanation: 'Automação com IA elimina tarefas repetitivas, libera tempo para trabalho estratégico e reduz erros.' },
        ],
      },
      {
        icon: '💳',
        title: 'Monetização com IA',
        description: 'Como ganhar dinheiro com produtos de IA.',
        topics: ['Modelos de negócio', 'SaaS com IA', 'Precificação', 'Cases de sucesso'],
        questions: [
          { icon: '💳', category: 'Negócios', difficulty: 'Fácil', text: 'O que é SaaS com IA?', options: ['Software de áudio', 'Software como serviço que usa IA como diferencial', 'Serviço de streaming', 'Sistema antispam'], correctIndex: 1, explanation: 'SaaS com IA são plataformas online que integram inteligência artificial para agregar valor ao produto.' },
          { icon: '💰', category: 'Negócios', difficulty: 'Fácil', text: 'Qual modelo de receita é mais comum em SaaS de IA?', options: ['Venda única', 'Assinatura mensal com tiers de uso', 'Doação', 'Publicidade'], correctIndex: 1, explanation: 'Assinaturas com diferentes planos (free, pro, enterprise) são o modelo mais comum.' },
          { icon: '📊', category: 'Negócios', difficulty: 'Médio', text: 'O que é "usage-based pricing" em IA?', options: ['Preço fixo', 'Cobrar com base na quantidade de uso (tokens, requests)', 'Preço por hora', 'Gratuito'], correctIndex: 1, explanation: 'Cobrança por uso permite escalar custos proporcionalmente ao consumo do cliente.' },
          { icon: '🎯', category: 'Negócios', difficulty: 'Médio', text: 'O que é um "AI wrapper"?', options: ['Embalagem de IA', 'Produto que adiciona interface/valor sobre uma API de IA existente', 'Tipo de modelo', 'Compressor de dados'], correctIndex: 1, explanation: 'AI wrappers constroem produtos especializados sobre APIs como GPT, adicionando UX e lógica de negócio.' },
          { icon: '🚀', category: 'Negócios', difficulty: 'Médio', text: 'Como validar uma ideia de produto com IA?', options: ['Construir tudo primeiro', 'Criar MVP rápido, testar com usuários e iterar', 'Fazer pesquisa por 1 ano', 'Copiar concorrentes'], correctIndex: 1, explanation: 'MVPs rápidos usando APIs de IA permitem validar a ideia com usuários reais antes de investir pesado.' },
          { icon: '🏆', category: 'Negócios', difficulty: 'Difícil', text: 'O que diferencia um bom produto de IA de um "wrapper" genérico?', options: ['Mais GPUs', 'Dados proprietários, UX superior e domínio específico', 'Logo bonito', 'Mais tokens'], correctIndex: 1, explanation: 'Produtos fortes têm dados únicos, UX refinada e profundo conhecimento do domínio do cliente.' },
          { icon: '📈', category: 'Negócios', difficulty: 'Difícil', text: 'O que é "moat" (fosso competitivo) em IA?', options: ['Castelo medieval', 'Vantagem difícil de copiar como dados, rede ou tecnologia', 'Marketing forte', 'Preço baixo'], correctIndex: 1, explanation: 'Moats em IA incluem dados proprietários, efeitos de rede, marca forte e tecnologia própria.' },
          { icon: '💡', category: 'Negócios', difficulty: 'Fácil', text: 'Freelancers podem usar IA para ganhar mais?', options: ['Não, IA substituiu freelancers', 'Sim, aumentando produtividade e oferecendo serviços de IA', 'Só empresas grandes', 'Apenas programadores'], correctIndex: 1, explanation: 'Freelancers que dominam IA podem entregar mais rápido e oferecer serviços premium como automações e chatbots.' },
        ],
      },
      {
        icon: '🏗️',
        title: 'Construindo Chatbots Inteligentes',
        description: 'Crie assistentes virtuais com IA para negócios.',
        topics: ['Arquitetura de chatbot', 'Contexto e memória', 'Deploy', 'Métricas'],
        questions: [
          { icon: '🤖', category: 'Chatbots', difficulty: 'Fácil', text: 'O que diferencia chatbot com IA de chatbot baseado em regras?', options: ['A cor da interface', 'IA entende linguagem natural e responde flexivelmente', 'O chatbot com IA é mais lento', 'Nada, são iguais'], correctIndex: 1, explanation: 'Chatbots com IA entendem intenção e contexto, enquanto chatbots de regras seguem fluxos fixos.' },
          { icon: '🧠', category: 'Chatbots', difficulty: 'Médio', text: 'O que é "context window" em chatbots?', options: ['Janela do navegador', 'Quantidade máxima de texto que o modelo pode processar por vez', 'Tamanho da tela', 'Duração da conversa'], correctIndex: 1, explanation: 'A context window limita quanto histórico de conversa o modelo pode considerar em cada resposta.' },
          { icon: '💾', category: 'Chatbots', difficulty: 'Médio', text: 'Como implementar memória em chatbots?', options: ['Usar cookies', 'Armazenar resumos de conversas e usar RAG', 'Gravar tela', 'Não é possível'], correctIndex: 1, explanation: 'Memória pode ser implementada resumindo conversas anteriores e buscando contexto relevante com RAG.' },
          { icon: '🎯', category: 'Chatbots', difficulty: 'Fácil', text: 'O que é "intent detection" em chatbots?', options: ['Detectar mentiras', 'Identificar o que o usuário quer fazer (intenção)', 'Prever o futuro', 'Análise de sentimento'], correctIndex: 1, explanation: 'Intent detection classifica a mensagem do usuário para entender sua intenção (comprar, reclamar, perguntar).' },
          { icon: '🔄', category: 'Chatbots', difficulty: 'Médio', text: 'O que é "fallback" em chatbots?', options: ['Queda do sistema', 'Resposta padrão quando o bot não entende a mensagem', 'Backup automático', 'Versão anterior'], correctIndex: 1, explanation: 'Fallback é acionado quando o chatbot não consegue entender ou responder adequadamente.' },
          { icon: '📊', category: 'Chatbots', difficulty: 'Difícil', text: 'Como medir a eficácia de um chatbot?', options: ['Pelo visual', 'Taxa de resolução, satisfação do usuário e taxa de transferência humana', 'Pelo custo', 'Pelo número de mensagens'], correctIndex: 1, explanation: 'Métricas chave incluem taxa de resolução sem humano, CSAT, tempo de resposta e handoff rate.' },
          { icon: '🌐', category: 'Chatbots', difficulty: 'Difícil', text: 'O que é "omnichannel" em chatbots?', options: ['Muitos canais de TV', 'Chatbot disponível em múltiplos canais com contexto compartilhado', 'Chat em grupo', 'Multi-idioma'], correctIndex: 1, explanation: 'Omnichannel permite que o chatbot funcione no WhatsApp, site, Instagram etc com histórico unificado.' },
          { icon: '🚀', category: 'Chatbots', difficulty: 'Fácil', text: 'Qual plataforma popular para criar chatbots com IA?', options: ['Excel', 'Botpress, Voiceflow ou Typebot', 'PowerPoint', 'Canva'], correctIndex: 1, explanation: 'Plataformas como Botpress e Voiceflow facilitam a criação de chatbots com IA sem muito código.' },
        ],
      },
      {
        icon: '🔮',
        title: 'O Futuro da IA',
        description: 'Tendências, riscos e oportunidades da IA.',
        topics: ['AGI', 'AI Safety', 'Empregos do futuro', 'Regulamentação global'],
        questions: [
          { icon: '🔮', category: 'Futuro', difficulty: 'Fácil', text: 'O que é AGI?', options: ['Tipo de GPU', 'Inteligência artificial com capacidade cognitiva geral humana', 'Framework de IA', 'Linguagem de programação'], correctIndex: 1, explanation: 'AGI seria uma IA capaz de realizar qualquer tarefa intelectual que um humano pode fazer.' },
          { icon: '🛡️', category: 'Futuro', difficulty: 'Médio', text: 'O que é AI Safety?', options: ['Antivírus para IA', 'Campo que estuda como garantir que IA seja segura e benéfica', 'Backup de modelos', 'Firewall de IA'], correctIndex: 1, explanation: 'AI Safety pesquisa como alinhar sistemas de IA com valores humanos e prevenir riscos existenciais.' },
          { icon: '💼', category: 'Futuro', difficulty: 'Médio', text: 'IA vai substituir todos os empregos?', options: ['Sim, completamente', 'Não, mas transformará muitos e criará novos', 'Não afetará nada', 'Só empregos manuais'], correctIndex: 1, explanation: 'IA automatizará tarefas, mas criará novas funções. Quem souber usar IA terá vantagem competitiva.' },
          { icon: '🌍', category: 'Futuro', difficulty: 'Médio', text: 'O que é o EU AI Act?', options: ['Conferência europeia', 'Primeira lei abrangente do mundo para regulamentar IA', 'App europeu', 'Modelo de IA europeu'], correctIndex: 1, explanation: 'O EU AI Act classifica sistemas de IA por risco e impõe requisitos de transparência e segurança.' },
          { icon: '🧬', category: 'Futuro', difficulty: 'Difícil', text: 'O que é "AI alignment problem"?', options: ['Bug de IA', 'Desafio de garantir que IA poderosa aja conforme valores humanos', 'Alinhamento de texto', 'Problema de GPU'], correctIndex: 1, explanation: 'O problema de alinhamento é um dos maiores desafios: como garantir que IA super-inteligente seja benéfica.' },
          { icon: '🤝', category: 'Futuro', difficulty: 'Fácil', text: 'Qual habilidade mais importante na era da IA?', options: ['Memorizar fatos', 'Saber fazer as perguntas certas e pensar criticamente', 'Digitar rápido', 'Saber programar em C'], correctIndex: 1, explanation: 'Pensamento crítico, criatividade e habilidade de direcionar IA serão as competências mais valiosas.' },
          { icon: '⚡', category: 'Futuro', difficulty: 'Difícil', text: 'O que é "AI governance"?', options: ['Governo de robôs', 'Frameworks para gestão responsável de IA em organizações', 'Eleição de IA', 'Tipo de modelo'], correctIndex: 1, explanation: 'AI governance define políticas, processos e responsabilidades para uso ético de IA nas empresas.' },
          { icon: '🚀', category: 'Futuro', difficulty: 'Difícil', text: 'O que é "compute governance"?', options: ['Governar computadores', 'Regular acesso a poder computacional para treinar IA', 'Cloud computing', 'Gerenciar data centers'], correctIndex: 1, explanation: 'Compute governance propõe regular o acesso a GPUs massivas como forma de controlar desenvolvimento de IA avançada.' },
        ],
      },
    ],
  },
];

export const FINAL_TEST_QUESTIONS = [
  { icon: '🤖', category: 'Fundamentos', difficulty: 'Médio' as const, text: 'Qual a principal diferença entre IA simbólica e IA conexionista?', options: ['Velocidade de processamento', 'Regras explícitas vs. aprendizado por padrões', 'Linguagem de programação usada', 'Custo de hardware'], correctIndex: 1, explanation: 'IA simbólica usa regras lógicas explícitas, enquanto IA conexionista aprende padrões a partir de dados.' },
  { icon: '🧠', category: 'Machine Learning', difficulty: 'Médio' as const, text: 'Qual tipo de aprendizado é usado quando não temos dados rotulados?', options: ['Supervisionado', 'Não supervisionado', 'Por reforço', 'Transfer Learning'], correctIndex: 1, explanation: 'O aprendizado não supervisionado encontra padrões em dados sem rótulos.' },
  { icon: '📊', category: 'Dados', difficulty: 'Fácil' as const, text: 'O que é "overfitting" em Machine Learning?', options: ['Modelo muito simples', 'Modelo que memoriza os dados de treino sem generalizar', 'Excesso de dados de treino', 'Modelo com poucos parâmetros'], correctIndex: 1, explanation: 'Overfitting ocorre quando o modelo aprende demais os detalhes dos dados de treino.' },
  { icon: '🔗', category: 'Deep Learning', difficulty: 'Difícil' as const, text: 'O que é uma função de ativação em redes neurais?', options: ['Função que liga o computador', 'Função que introduz não-linearidade nas camadas', 'Algoritmo de otimização', 'Método de coleta de dados'], correctIndex: 1, explanation: 'Funções de ativação permitem que redes neurais aprendam relações complexas e não-lineares.' },
  { icon: '💬', category: 'NLP', difficulty: 'Médio' as const, text: 'O que significa "tokenização" em NLP?', options: ['Criptografar texto', 'Dividir texto em unidades menores (tokens)', 'Traduzir entre idiomas', 'Comprimir arquivos'], correctIndex: 1, explanation: 'Tokenização divide texto em pedaços para que modelos de IA possam processá-los.' },
  { icon: '🎯', category: 'Modelos', difficulty: 'Difícil' as const, text: 'O que é o mecanismo de "Attention" em Transformers?', options: ['Filtro de spam', 'Permite o modelo focar em partes relevantes da entrada', 'Sistema de cache', 'Técnica de compressão'], correctIndex: 1, explanation: 'Attention permite que o modelo pondere a importância de cada parte da entrada.' },
  { icon: '⚡', category: 'Prática', difficulty: 'Fácil' as const, text: 'Qual dessas é uma aplicação real de IA generativa?', options: ['Calculadora simples', 'Geração de imagens a partir de texto', 'Planilha de Excel', 'Envio de e-mails automáticos'], correctIndex: 1, explanation: 'IA generativa como DALL-E cria imagens originais a partir de descrições em texto.' },
  { icon: '⚖️', category: 'Ética', difficulty: 'Médio' as const, text: 'O que é "explicabilidade" (XAI) em IA?', options: ['Manual de instrução', 'Capacidade de entender e justificar decisões do modelo', 'Velocidade de resposta', 'Interface do usuário'], correctIndex: 1, explanation: 'XAI busca tornar decisões de IA transparentes e compreensíveis.' },
  { icon: '🔄', category: 'MLOps', difficulty: 'Difícil' as const, text: 'O que é "model drift" em produção?', options: ['Bug no código', 'Degradação quando dados reais mudam ao longo do tempo', 'Modelo lento', 'Erro de deploy'], correctIndex: 1, explanation: 'Model drift acontece quando a distribuição dos dados muda, fazendo o modelo perder performance.' },
  { icon: '🚀', category: 'Futuro', difficulty: 'Médio' as const, text: 'O que é AGI (Artificial General Intelligence)?', options: ['IA para jogos', 'IA com capacidade cognitiva geral equivalente à humana', 'Tipo de GPU', 'Framework de ML'], correctIndex: 1, explanation: 'AGI seria uma IA capaz de qualquer tarefa intelectual humana. Ainda é teórica.' },
];

export const SECTION_FINAL_TESTS: Record<string, typeof FINAL_TEST_QUESTIONS> = {
  'section-1': FINAL_TEST_QUESTIONS,
  'section-2': [
    { icon: '🎭', category: 'Prompting', difficulty: 'Médio' as const, text: 'O que é "role prompting"?', options: ['Dar cargo ao dev', 'Atribuir persona ao modelo', 'Criar RPG', 'Definir permissões'], correctIndex: 1, explanation: 'Role prompting define um papel para a IA.' },
    { icon: '📚', category: 'RAG', difficulty: 'Médio' as const, text: 'O que é RAG?', options: ['Linguagem', 'Combinar busca com geração de texto', 'Rede neural', 'Framework'], correctIndex: 1, explanation: 'RAG busca informações e usa como contexto para gerar respostas.' },
    { icon: '🤖', category: 'Agentes', difficulty: 'Difícil' as const, text: 'O que é o padrão ReAct?', options: ['Framework React', 'Alternar raciocínio e ação', 'Reação química', 'Reactive programming'], correctIndex: 1, explanation: 'ReAct alterna entre raciocínio e ação para resolver problemas.' },
    { icon: '🧬', category: 'Fine-tuning', difficulty: 'Difícil' as const, text: 'O que é LoRA?', options: ['Protocolo de rede', 'Fine-tuning eficiente com poucos parâmetros', 'Linguagem', 'GPU'], correctIndex: 1, explanation: 'LoRA treina matrizes de baixo rank, reduzindo custo de fine-tuning.' },
    { icon: '📊', category: 'Avaliação', difficulty: 'Médio' as const, text: 'O que é alucinação em LLMs?', options: ['Bug visual', 'Gerar informação falsa com confiança', 'Efeito de GPU', 'Texto corrompido'], correctIndex: 1, explanation: 'Alucinação é quando o modelo inventa fatos aparentemente verdadeiros.' },
    { icon: '🔍', category: 'RAG', difficulty: 'Difícil' as const, text: 'O que é hybrid search?', options: ['Busca bilíngue', 'Combinar busca semântica com keyword', 'Dois bancos', 'Dois modelos'], correctIndex: 1, explanation: 'Hybrid search combina busca vetorial com lexical.' },
    { icon: '🧩', category: 'Prompting', difficulty: 'Difícil' as const, text: 'O que é Tree of Thoughts?', options: ['Árvore de decisão', 'Explorar múltiplos caminhos de raciocínio', 'Estrutura de dados', 'Organograma'], correctIndex: 1, explanation: 'ToT explora diferentes linhas de raciocínio antes de escolher.' },
    { icon: '🛡️', category: 'Agentes', difficulty: 'Médio' as const, text: 'O que são guardrails?', options: ['Proteção física', 'Limites de segurança para controlar o agente', 'Firewall', 'Antivírus'], correctIndex: 1, explanation: 'Guardrails impedem ações perigosas ou fora do escopo.' },
    { icon: '📏', category: 'Avaliação', difficulty: 'Difícil' as const, text: 'O que é ELO rating para LLMs?', options: ['Ranking de xadrez', 'Classificação por comparações diretas', 'Nota escolar', 'Benchmark'], correctIndex: 1, explanation: 'ELO classifica LLMs via preferências humanas em comparações cegas.' },
    { icon: '🔧', category: 'Fine-tuning', difficulty: 'Médio' as const, text: 'O que é catastrophic forgetting?', options: ['Bug de memória', 'Esquecer conhecimento anterior ao aprender novo', 'Perda de dados', 'Crash'], correctIndex: 1, explanation: 'Fine-tuning agressivo pode fazer o modelo esquecer capacidades gerais.' },
  ],
  'section-3': [
    { icon: '🎨', category: 'Imagens', difficulty: 'Médio' as const, text: 'O que são diffusion models?', options: ['Modelos que difundem', 'Aprendem a remover ruído para gerar imagens', 'Filtros', 'Propagação'], correctIndex: 1, explanation: 'Diffusion models geram imagens aprendendo a desruidar.' },
    { icon: '🗣️', category: 'Áudio', difficulty: 'Fácil' as const, text: 'O que é TTS?', options: ['Tipo de arquivo', 'Converte texto em fala', 'Protocolo', 'Editor'], correctIndex: 1, explanation: 'TTS transforma texto em fala natural.' },
    { icon: '🎬', category: 'Vídeo', difficulty: 'Médio' as const, text: 'O que é Sora?', options: ['Editor', 'Gera vídeos a partir de texto', 'Rede social', 'Câmera'], correctIndex: 1, explanation: 'Sora gera vídeos fotorrealistas a partir de descrições.' },
    { icon: '💻', category: 'Código', difficulty: 'Fácil' as const, text: 'O que é Copilot?', options: ['Premium GitHub', 'Assistente de IA para código', 'Browser', 'Chat'], correctIndex: 1, explanation: 'Copilot sugere código em tempo real.' },
    { icon: '🌐', category: 'Multimodal', difficulty: 'Médio' as const, text: 'O que é modelo multimodal?', options: ['Vários modos', 'Processa texto, imagem e áudio', 'Várias versões', 'Multilíngue'], correctIndex: 1, explanation: 'Modelos multimodais processam múltiplos tipos de dados.' },
    { icon: '🎭', category: 'Imagens', difficulty: 'Difícil' as const, text: 'O que é ControlNet?', options: ['Firewall', 'Controla composição na geração', 'Rede de controle', 'Gerenciador'], correctIndex: 1, explanation: 'ControlNet controla pose, bordas e profundidade na geração.' },
    { icon: '😱', category: 'Vídeo', difficulty: 'Difícil' as const, text: 'O que é deepfake?', options: ['4K', 'Vídeo falso com IA', 'Efeito especial', 'Vídeo rápido'], correctIndex: 1, explanation: 'Deepfakes usam IA para criar vídeos falsos convincentes.' },
    { icon: '🔄', category: 'Multimodal', difficulty: 'Difícil' as const, text: 'O que é cross-modal understanding?', options: ['Dois idiomas', 'Relacionar informações entre mídias', 'Converter formatos', 'Traduzir'], correctIndex: 1, explanation: 'É conectar conceitos entre modalidades diferentes.' },
    { icon: '🔒', category: 'Código', difficulty: 'Difícil' as const, text: 'Qual risco de código gerado por IA?', options: ['Muito rápido', 'Vulnerabilidades não detectadas', 'Muito documentado', 'Muito curto'], correctIndex: 1, explanation: 'Código de IA pode ter vulnerabilidades sutis.' },
    { icon: '⚠️', category: 'Áudio', difficulty: 'Médio' as const, text: 'O que são deepfakes de áudio?', options: ['Música eletrônica', 'Áudios falsos que imitam vozes reais', 'Efeitos sonoros', 'Compressão'], correctIndex: 1, explanation: 'Deepfakes de áudio criam gravações falsas convincentes.' },
  ],
  'section-4': [
    { icon: '🔌', category: 'APIs', difficulty: 'Fácil' as const, text: 'O que é uma API de IA?', options: ['Interface gráfica', 'Interface para acessar modelos programaticamente', 'Rede social', 'Tipo de modelo'], correctIndex: 1, explanation: 'APIs permitem integrar modelos de IA em aplicações.' },
    { icon: '⚡', category: 'Automação', difficulty: 'Médio' as const, text: 'O que é n8n?', options: ['Linguagem', 'Plataforma de automação visual', 'Rede social', 'Banco de dados'], correctIndex: 1, explanation: 'n8n permite criar automações conectando serviços via interface visual.' },
    { icon: '💳', category: 'Negócios', difficulty: 'Médio' as const, text: 'O que é um AI wrapper?', options: ['Embalagem', 'Produto sobre API de IA existente', 'Tipo de modelo', 'Compressor'], correctIndex: 1, explanation: 'AI wrappers constroem produtos especializados sobre APIs de IA.' },
    { icon: '🤖', category: 'Chatbots', difficulty: 'Fácil' as const, text: 'O que diferencia chatbot com IA?', options: ['Cor da interface', 'Entende linguagem natural flexivelmente', 'É mais lento', 'São iguais'], correctIndex: 1, explanation: 'Chatbots com IA entendem intenção e contexto.' },
    { icon: '🔮', category: 'Futuro', difficulty: 'Médio' as const, text: 'O que é AI Safety?', options: ['Antivírus', 'Garantir que IA seja segura e benéfica', 'Backup', 'Firewall'], correctIndex: 1, explanation: 'AI Safety pesquisa como alinhar IA com valores humanos.' },
    { icon: '🔄', category: 'APIs', difficulty: 'Difícil' as const, text: 'O que é function calling?', options: ['Ligar para suporte', 'Permitir que LLM invoque ferramentas externas', 'JavaScript', 'Recursão'], correctIndex: 1, explanation: 'Function calling permite que o LLM use ferramentas externas.' },
    { icon: '🤝', category: 'Futuro', difficulty: 'Difícil' as const, text: 'O que é AI governance?', options: ['Governo de robôs', 'Frameworks para gestão responsável de IA', 'Eleição', 'Modelo'], correctIndex: 1, explanation: 'AI governance define políticas para uso ético de IA.' },
    { icon: '📊', category: 'Chatbots', difficulty: 'Difícil' as const, text: 'Como medir eficácia de chatbot?', options: ['Visual', 'Taxa de resolução e satisfação', 'Custo', 'Mensagens'], correctIndex: 1, explanation: 'Métricas chave: resolução, CSAT, tempo de resposta e handoff rate.' },
    { icon: '🏆', category: 'Negócios', difficulty: 'Difícil' as const, text: 'O que é moat em IA?', options: ['Castelo', 'Vantagem difícil de copiar', 'Marketing', 'Preço baixo'], correctIndex: 1, explanation: 'Moats incluem dados proprietários, rede e tecnologia própria.' },
    { icon: '💼', category: 'Futuro', difficulty: 'Fácil' as const, text: 'IA vai substituir todos os empregos?', options: ['Sim', 'Não, mas transformará e criará novos', 'Não afetará', 'Só manuais'], correctIndex: 1, explanation: 'IA transformará empregos. Quem souber usá-la terá vantagem.' },
  ],
};

export const INITIAL_PLAYER = {
  xp: 2800,
  streak: 3,
  level: 29,
  levelTitle: 'Data Analyst',
  currentXp: 2800,
  nextLevelXp: 4500,
  completedLessons: [] as number[],
};
